a = int(input("a = "))
b = int(input("b = "))
c = int(input("c = "))
d = float(a ** 2 + b ** 2) / (b * 3 - 4)
e = float(4 * c ** 5 / 6)
f = float(d // e)
g = float(d % e)
print(f"Целая часть: {float(f)}")
print(f"Остаток от деления: {float(g)}")